apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: captainchain-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: captainchain.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: captainchain-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: captainchain-frontend
                port:
                  number: 3000
